#Load Libraries
library(data.table)
library(dplyr)
library(tidyverse)

#upload the read count matrix of human, antibody and microbes that is generated by BD Rhapsody platform for each sample.
cc_sample1 <- fread("B1_RSEC_MolsPerCell.csv")

#OR
#Alternatively load RDS file saved from STARsolo alignment
cc_sample1 <-loadRDS("<samplename>_RSEC_MolsPerCell.rds")

#Get gene list from the count matrix: 
countmat_gene_list1 <- colnames(cc_sample1)

#renaming the column name 
cc_sample1 <- t(cc_sample1)
colnames(cc_sample1) <- cc_sample1[1,]
cc_sample1 <- cc_sample1[-1,]

#upload microbial gene list 
microbe_gl <- as.vector(read.csv("path/to/BAnthracis_genes.csv"))

#check if these genes are there in the raw data 
genes_microbe_gl_found <- intersect(countmat_gene_list1, microbe_gl$genes)

#number of microbial genes found in count matrix
length(genes_microbe_gl_found)
#subset original/raw data based on above pathogen genes
microbe_gl_mat <- cc_sample1[row.names(cc_sample1) %in%    genes_microbe_gl_found, ]

# Get read count for that particular pathogen species 
microbe_gl_mat <- as.data.frame(microbe_gl_mat)
dim(microbe_gl_mat)

col<-ncol(microbe_gl_mat)
#concatenate all the genes in a single column 
microbe_gl_mat_sum <- colSums(microbe_gl_mat[, 1:col]) 
BAnthracis_gl_mat_sum <-as.data.frame(microbe_gl_mat_sum)
BAnthracis_gl_mat_sum <- t(BAnthracis_gl_mat_sum)
dim(BAnthracis_gl_mat_sum)
BAnthracis_gl_mat_sum <-as.data.frame(BAnthracis_gl_mat_sum)


#Save the row name as that microbial species name
rownames(BAnthracis_gl_mat_sum) <- "Baccillus_Anthracis"
#concatenate all the microbial read count matrix  
sample1_mat<-list(BAnthracis_gl_mat_sum,Bthurigenesis_mat_sum, Bdutonii_mat_sum, Tgeofonti_mat_sum)

#combined all the microbial row
sample1_mat <- do.call(rbind, sample1_mat)

# Write the combined matrix to a CSV file
write.csv(sample1_mat , "sample1_microbe_count_matrix.csv")


#Extract antibody read count matrix
all_antibody_genes <- as.vector(read.csv("antibody_list.txt")) 

# check if these genes are there in the gene list  
all_antibody_genes_found <- intersect(countmat_gene_list1, all_antibody_genes$Genes)

# number of genes 
length(all_antibody_genes_found)

#subset original/raw data based on above pathogen genes 
abseq_mat <- cc_sample1[row.names(cc_sample1) %in% all_antibody_genes_found, ] 

#Total Read Count Value of the matrix 
sum(abseq_mat)

# save antibody count matrix in CSV file  
write.csv(abseq_mat,"sample1_abseq_count_matrix.csv")

#Extract count matrix excluded microbes and antibody genes
#Read all combined pathogenic genes  

all_microbes_genes <-as.vector(read.csv("all_microbes_genes.txt"))

all_microbes_genes_found <- intersect(countmat_gene_list1,all_microbes_genes$Genes)

# Number of Non-zero values in matrix 
length(all_microbes_genes_found)

#exclude microbial genes  
microbes_only_sample1 <- cc_sample1[!row.names(cc_sample1) %in% all_microbes_genes_found, ]
dim(microbes_only_sample1)
colnames(microbes_only_sample1) <- microbes_only_sample1[1,]
microbes_only_sample1 <- microbes_only_sample1[-1,]

dim(microbes_only_sample1)

#exclude antibody genes 
Human_wta <- microbes_only_sample1[!row.names(microbes_only_sample1) %in% all_antibody_genes_found, ]
dim(human_wta)

#save the human count matrix
write.csv(human_wta,"sample1_human_count_matrix.csv")
############Do the same for all samples.#########


